# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/company_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/company_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/company_service.proto\x12\x0e\x63ompanyservice\"q\n\x14\x43reateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x12\n\ntrade_name\x18\x03 \x01(\t\x12\x1b\n\x13registration_number\x18\x04 \x01(\t\"P\n\x15\x43reateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncompany_id\x18\x03 \x01(\t\">\n\x18\x44\x65\x61\x63tivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"T\n\x19\x44\x65\x61\x63tivateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncompany_id\x18\x03 \x01(\t\">\n\x18ReactivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"T\n\x19ReactivateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncompany_id\x18\x03 \x01(\t2\xc2\x02\n\x0e\x43ompanyService\x12\\\n\rCreateCompany\x12$.companyservice.CreateCompanyRequest\x1a%.companyservice.CreateCompanyResponse\x12h\n\x11\x44\x65\x61\x63tivateCompany\x12(.companyservice.DeactivateCompanyRequest\x1a).companyservice.DeactivateCompanyResponse\x12h\n\x11ReactivateCompany\x12(.companyservice.ReactivateCompanyRequest\x1a).companyservice.ReactivateCompanyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.company_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOMPANYREQUEST']._serialized_start=47
  _globals['_CREATECOMPANYREQUEST']._serialized_end=160
  _globals['_CREATECOMPANYRESPONSE']._serialized_start=162
  _globals['_CREATECOMPANYRESPONSE']._serialized_end=242
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_start=244
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_end=306
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_start=308
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_end=392
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_start=394
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_end=456
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_start=458
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_end=542
  _globals['_COMPANYSERVICE']._serialized_start=545
  _globals['_COMPANYSERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
