# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import company_service_pb2 as proto_dot_company__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/company_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanyServiceStub(object):
    """CompanyService service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCompany = channel.unary_unary(
                '/companyservice.CompanyService/CreateCompany',
                request_serializer=proto_dot_company__service__pb2.CreateCompanyRequest.SerializeToString,
                response_deserializer=proto_dot_company__service__pb2.CreateCompanyResponse.FromString,
                _registered_method=True)
        self.DeactivateCompany = channel.unary_unary(
                '/companyservice.CompanyService/DeactivateCompany',
                request_serializer=proto_dot_company__service__pb2.DeactivateCompanyRequest.SerializeToString,
                response_deserializer=proto_dot_company__service__pb2.DeactivateCompanyResponse.FromString,
                _registered_method=True)
        self.ReactivateCompany = channel.unary_unary(
                '/companyservice.CompanyService/ReactivateCompany',
                request_serializer=proto_dot_company__service__pb2.ReactivateCompanyRequest.SerializeToString,
                response_deserializer=proto_dot_company__service__pb2.ReactivateCompanyResponse.FromString,
                _registered_method=True)


class CompanyServiceServicer(object):
    """CompanyService service definition
    """

    def CreateCompany(self, request, context):
        """Create a new company
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateCompany(self, request, context):
        """Deactivate a company's license
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactivateCompany(self, request, context):
        """Reactivate a company's license
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCompany,
                    request_deserializer=proto_dot_company__service__pb2.CreateCompanyRequest.FromString,
                    response_serializer=proto_dot_company__service__pb2.CreateCompanyResponse.SerializeToString,
            ),
            'DeactivateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateCompany,
                    request_deserializer=proto_dot_company__service__pb2.DeactivateCompanyRequest.FromString,
                    response_serializer=proto_dot_company__service__pb2.DeactivateCompanyResponse.SerializeToString,
            ),
            'ReactivateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactivateCompany,
                    request_deserializer=proto_dot_company__service__pb2.ReactivateCompanyRequest.FromString,
                    response_serializer=proto_dot_company__service__pb2.ReactivateCompanyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companyservice.CompanyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companyservice.CompanyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanyService(object):
    """CompanyService service definition
    """

    @staticmethod
    def CreateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/CreateCompany',
            proto_dot_company__service__pb2.CreateCompanyRequest.SerializeToString,
            proto_dot_company__service__pb2.CreateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/DeactivateCompany',
            proto_dot_company__service__pb2.DeactivateCompanyRequest.SerializeToString,
            proto_dot_company__service__pb2.DeactivateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReactivateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/ReactivateCompany',
            proto_dot_company__service__pb2.ReactivateCompanyRequest.SerializeToString,
            proto_dot_company__service__pb2.ReactivateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
