# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from app.protos import company_pb2 as app_dot_protos_dot_company__pb2


class CompanyServiceStub(object):
    """Company service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCompany = channel.unary_unary(
                '/companyservice.CompanyService/CreateCompany',
                request_serializer=app_dot_protos_dot_company__pb2.CreateCompanyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_company__pb2.CreateCompanyResponse.FromString,
                )
        self.DeactivateCompany = channel.unary_unary(
                '/companyservice.CompanyService/DeactivateCompany',
                request_serializer=app_dot_protos_dot_company__pb2.DeactivateCompanyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_company__pb2.DeactivateCompanyResponse.FromString,
                )
        self.ReactivateCompany = channel.unary_unary(
                '/companyservice.CompanyService/ReactivateCompany',
                request_serializer=app_dot_protos_dot_company__pb2.ReactivateCompanyRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_company__pb2.ReactivateCompanyResponse.FromString,
                )


class CompanyServiceServicer(object):
    """Company service definition
    """

    def CreateCompany(self, request, context):
        """Create a new company
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateCompany(self, request, context):
        """Deactivate a company's license
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReactivateCompany(self, request, context):
        """Reactivate a company's license
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCompany,
                    request_deserializer=app_dot_protos_dot_company__pb2.CreateCompanyRequest.FromString,
                    response_serializer=app_dot_protos_dot_company__pb2.CreateCompanyResponse.SerializeToString,
            ),
            'DeactivateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateCompany,
                    request_deserializer=app_dot_protos_dot_company__pb2.DeactivateCompanyRequest.FromString,
                    response_serializer=app_dot_protos_dot_company__pb2.DeactivateCompanyResponse.SerializeToString,
            ),
            'ReactivateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.ReactivateCompany,
                    request_deserializer=app_dot_protos_dot_company__pb2.ReactivateCompanyRequest.FromString,
                    response_serializer=app_dot_protos_dot_company__pb2.ReactivateCompanyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companyservice.CompanyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CompanyService(object):
    """Company service definition
    """

    @staticmethod
    def CreateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/CreateCompany',
            app_dot_protos_dot_company__pb2.CreateCompanyRequest.SerializeToString,
            app_dot_protos_dot_company__pb2.CreateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def DeactivateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/DeactivateCompany',
            app_dot_protos_dot_company__pb2.DeactivateCompanyRequest.SerializeToString,
            app_dot_protos_dot_company__pb2.DeactivateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)

    @staticmethod
    def ReactivateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyservice.CompanyService/ReactivateCompany',
            app_dot_protos_dot_company__pb2.ReactivateCompanyRequest.SerializeToString,
            app_dot_protos_dot_company__pb2.ReactivateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata)
