# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/company.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/protos/company.proto\x12\x0f\x63ompanyservice\"r\n\x14\x43reateCompanyRequest\x12\x1b\n\x13legal_entity_registration\x18\x01 \x01(\t\x12\x12\n\ncompany_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x12\n\ntrade_name\x18\x04 \x01(\t\"J\n\x15\x43reateCompanyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncommand_id\x18\x03 \x01(\t\"5\n\x18\x44\x65\x61\x63tivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"J\n\x19\x44\x65\x61\x63tivateCompanyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncommand_id\x18\x03 \x01(\t\"5\n\x18ReactivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"J\n\x19ReactivateCompanyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncommand_id\x18\x03 \x01(\t2\x9b\x02\n\x0f\x43ompanyService\x12R\n\rCreateCompany\x12\x25.companyservice.CreateCompanyRequest\x1a\x26.companyservice.CreateCompanyResponse\x12\\\n\x11\x44\x65\x61\x63tivateCompany\x12).companyservice.DeactivateCompanyRequest\x1a*.companyservice.DeactivateCompanyResponse\x12^\n\x11ReactivateCompany\x12).companyservice.ReactivateCompanyRequest\x1a*.companyservice.ReactivateCompanyResponse\x62\x06proto3')

_globals = globals()
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateCompanyRequest = _sym_db.GetSymbol('companyservice.CreateCompanyRequest')
CreateCompanyResponse = _sym_db.GetSymbol('companyservice.CreateCompanyResponse')
DeactivateCompanyRequest = _sym_db.GetSymbol('companyservice.DeactivateCompanyRequest')
DeactivateCompanyResponse = _sym_db.GetSymbol('companyservice.DeactivateCompanyResponse')
ReactivateCompanyRequest = _sym_db.GetSymbol('companyservice.ReactivateCompanyRequest')
ReactivateCompanyResponse = _sym_db.GetSymbol('companyservice.ReactivateCompanyResponse')

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATECOMPANYREQUEST']._serialized_start=37
  _globals['_CREATECOMPANYREQUEST']._serialized_end=155
  _globals['_CREATECOMPANYRESPONSE']._serialized_start=157
  _globals['_CREATECOMPANYRESPONSE']._serialized_end=231
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_start=233
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_end=286
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_start=288
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_end=362
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_start=364
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_end=417
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_start=419
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_end=493
  _globals['_COMPANYSERVICE']._serialized_start=496
  _globals['_COMPANYSERVICE']._serialized_end=787
