# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/protos/company.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'app/protos/company.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/protos/company.proto\x12\x07\x63ompany\"q\n\x14\x43reateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x12\n\ntrade_name\x18\x03 \x01(\t\x12\x1b\n\x13registration_number\x18\x04 \x01(\t\"<\n\x15\x43reateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x18\x44\x65\x61\x63tivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"@\n\x19\x44\x65\x61\x63tivateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\">\n\x18ReactivateCompanyRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"@\n\x19ReactivateCompanyResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x95\x02\n\x07\x43ompany\x12P\n\rCreateCompany\x12\x1d.company.CreateCompanyRequest\x1a\x1e.company.CreateCompanyResponse0\x01\x12Z\n\x11\x44\x65\x61\x63tivateCompany\x12!.company.DeactivateCompanyRequest\x1a\".company.DeactivateCompanyResponse\x12\\\n\x11ReactivateCompany\x12!.company.ReactivateCompanyRequest\x1a\".company.ReactivateCompanyResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.company_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECOMPANYREQUEST']._serialized_start=37
  _globals['_CREATECOMPANYREQUEST']._serialized_end=150
  _globals['_CREATECOMPANYRESPONSE']._serialized_start=152
  _globals['_CREATECOMPANYRESPONSE']._serialized_end=212
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_start=214
  _globals['_DEACTIVATECOMPANYREQUEST']._serialized_end=276
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_start=278
  _globals['_DEACTIVATECOMPANYRESPONSE']._serialized_end=342
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_start=344
  _globals['_REACTIVATECOMPANYREQUEST']._serialized_end=406
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_start=408
  _globals['_REACTIVATECOMPANYRESPONSE']._serialized_end=472
  _globals['_COMPANY']._serialized_start=475
  _globals['_COMPANY']._serialized_end=752
# @@protoc_insertion_point(module_scope)
